print("")
print("Hello, do you want to play a game?")
print("")
input("Press ENTER to play...")
print("")
print("Please name an animal...")
print("")
animal = input(">>> ")
print("")
print("Please name a city...")
print("")
city = input(">>> ")
print("")
print("Please name a season...")
print("")
season = input(">>> ")
print("")
print("Please name an emotion...")
print("")
emotion = input(">>> ")
print("")
print("Thanks, generating your story now...")
print("___")
print("___")
print("___")
print("___")
print("___")
print(f"During {season}, a {emotion} {animal}, was riding his vespa through the streets of {city}")
print("")
print("Thanks for playing!")
print("")